version: '3.7'
services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat-server
    ports:
      - "8080:8080"
    volumes:
      - ./_data/logs:/usr/local/tomcat/logs
    networks:
      tomcat-net:
        aliases:
          - tomcat.host
networks:
  tomcat-net:
    driver: bridge
    ipam:
      driver: default
